export default {
    // private
    dashboard: '/page/dashboard',
    buttons: '/page/buttons',
    charts: '/page/charts',
    colors: '/page/colors',
	errormessages: '/page/error-messages',
	forminput:'/page/form-input',
    icons: '/page/icons',
    loaders: '/page/loader-and-loadings',
    logos: '/page/logos',
    links: '/page/notifications-and-tooltip',
    panels: '/page/panels',
	richtext: '/page/rich-text-editor',
	table: '/page/tables',
	tabs: '/page/tabs',
	timeline: '/page/timeline',
	treeview: '/page/treeview',
	typography: '/page/typography',
};
